// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBThUz7LR9-dYyrIqRS4lW390NcmpRPD24',
    appId: '1:258424811835:web:4b12373c1d337af112871e',
    messagingSenderId: '258424811835',
    projectId: 'agenda-etudiant-f3ff3',
    authDomain: 'agenda-etudiant-f3ff3.firebaseapp.com',
    databaseURL: 'https://agenda-etudiant-f3ff3-default-rtdb.firebaseio.com',
    storageBucket: 'agenda-etudiant-f3ff3.firebasestorage.app',
    measurementId: 'G-HYE44C9M32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAuryg8BNH1gpP_lM_O2dx8UoL-gfDwKc',
    appId: '1:258424811835:android:52a5700227ac7a1d12871e',
    messagingSenderId: '258424811835',
    projectId: 'agenda-etudiant-f3ff3',
    databaseURL: 'https://agenda-etudiant-f3ff3-default-rtdb.firebaseio.com',
    storageBucket: 'agenda-etudiant-f3ff3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuRqdaeqgb6xXhQpgf9Ymek81U6-fMm3w',
    appId: '1:258424811835:ios:f63eb80ed06ce9de12871e',
    messagingSenderId: '258424811835',
    projectId: 'agenda-etudiant-f3ff3',
    databaseURL: 'https://agenda-etudiant-f3ff3-default-rtdb.firebaseio.com',
    storageBucket: 'agenda-etudiant-f3ff3.firebasestorage.app',
    iosBundleId: 'com.example.studentManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuRqdaeqgb6xXhQpgf9Ymek81U6-fMm3w',
    appId: '1:258424811835:ios:f63eb80ed06ce9de12871e',
    messagingSenderId: '258424811835',
    projectId: 'agenda-etudiant-f3ff3',
    databaseURL: 'https://agenda-etudiant-f3ff3-default-rtdb.firebaseio.com',
    storageBucket: 'agenda-etudiant-f3ff3.firebasestorage.app',
    iosBundleId: 'com.example.studentManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBThUz7LR9-dYyrIqRS4lW390NcmpRPD24',
    appId: '1:258424811835:web:4a070a259473412812871e',
    messagingSenderId: '258424811835',
    projectId: 'agenda-etudiant-f3ff3',
    authDomain: 'agenda-etudiant-f3ff3.firebaseapp.com',
    databaseURL: 'https://agenda-etudiant-f3ff3-default-rtdb.firebaseio.com',
    storageBucket: 'agenda-etudiant-f3ff3.firebasestorage.app',
    measurementId: 'G-SLX6P97XES',
  );
}
